export type LicenseMeta = {
  description: string;
  descriptionEn: string;
  requirements: string[];
  requirementsEn: string[];
  documents: string[];
  documentsEn: string[];
  eligibility: string[];
  eligibilityEn: string[];
  lastSyncedAt: string;
  lastOfficialUpdate: string;
  sourceUrl: string;
  verified: boolean;
  stale?: boolean;
};

export const META: Record<string, LicenseMeta> = {
  cr: {
    description: "السجل التجاري وثيقة رسمية تُثبت مزاولة النشاط التجاري وفق نظام السجل التجاري.",
    descriptionEn: "Official document proving commercial activity per the Commercial Registration Law.",
    requirements: ["أن يكون المتقدم سعودي أو مقيم نظامي", "لا يوجد سجل تجاري مماثل لنفس النشاط"],
    requirementsEn: ["Saudi citizen or legal resident", "No duplicate CR for same activity"],
    documents: ["الهوية الوطنية / الإقامة", "تحديد الاسم التجاري", "عنوان وطني"],
    documentsEn: ["National ID / Iqama", "Trade name", "National address"],
    eligibility: ["العمر ١٨ سنة فأعلى", "الأهلية القانونية الكاملة"],
    eligibilityEn: ["Age 18+", "Full legal capacity"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٨ ٠٩:١٢",
    lastOfficialUpdate: "٢٠٢٦/٠٥/١٤",
    sourceUrl: "https://mc.gov.sa",
    verified: true,
  },
  municipal: {
    description: "رخصة تصدرها البلدية لممارسة النشاط في موقع محدد وفق اشتراطات السلامة والصحة.",
    descriptionEn: "Municipal license to operate at a specific location per safety and health rules.",
    requirements: ["سجل تجاري ساري", "عقد إيجار موثق (إيجار)", "مخطط الموقع"],
    requirementsEn: ["Valid CR", "Ejar-verified lease", "Site plan"],
    documents: ["السجل التجاري", "عقد إيجار", "شهادة الدفاع المدني"],
    documentsEn: ["Commercial Registration", "Lease contract", "Civil Defense certificate"],
    eligibility: ["موقع مطابق لاشتراطات البلدية"],
    eligibilityEn: ["Location compliant with municipal code"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٩ ١٤:٠٠",
    lastOfficialUpdate: "٢٠٢٦/٠٣/١٨",
    sourceUrl: "https://balady.gov.sa",
    verified: true,
  },
  chamber: {
    description: "عضوية الغرفة التجارية تتيح لك خدمات التصديق والدعم التجاري.",
    descriptionEn: "Chamber membership unlocks attestation and trade support services.",
    requirements: ["سجل تجاري ساري"],
    requirementsEn: ["Valid CR"],
    documents: ["السجل التجاري", "الهوية الوطنية"],
    documentsEn: ["Commercial Registration", "National ID"],
    eligibility: ["منشأة مسجلة"],
    eligibilityEn: ["Registered establishment"],
    lastSyncedAt: "٢٠٢٦/٠٦/٣٠ ٠٨:٤٥",
    lastOfficialUpdate: "٢٠٢٥/١١/٠١",
    sourceUrl: "https://fsc.org.sa",
    verified: true,
  },
  health: {
    description: "شهادة صحية إلزامية لجميع العاملين في القطاع الغذائي.",
    descriptionEn: "Mandatory health certificate for all food-sector workers.",
    requirements: ["فحص طبي معتمد", "دورة السلامة الغذائية"],
    requirementsEn: ["Approved medical exam", "Food safety course"],
    documents: ["الهوية / الإقامة", "نتيجة الفحص الطبي"],
    documentsEn: ["ID / Iqama", "Medical exam result"],
    eligibility: ["كل عامل على تماس مباشر بالغذاء"],
    eligibilityEn: ["Any worker in direct food contact"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٧ ١٦:٣٠",
    lastOfficialUpdate: "٢٠٢٦/٠٢/١٠",
    sourceUrl: "https://moh.gov.sa",
    verified: true,
  },
  food: {
    description: "ترخيص السلامة الغذائية من هيئة الغذاء والدواء للمنشآت الغذائية.",
    descriptionEn: "SFDA food safety license for food establishments.",
    requirements: ["مطابقة اشتراطات SFDA", "مسؤول سلامة غذائية"],
    requirementsEn: ["SFDA compliance", "Food safety officer"],
    documents: ["السجل التجاري", "رخصة البلدية", "شهادة السلامة"],
    documentsEn: ["Commercial Registration", "Municipal license", "Safety certificate"],
    eligibility: ["منشأة غذائية مرخصة بلدياً"],
    eligibilityEn: ["Municipally-licensed food establishment"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٨ ١١:٠٠",
    lastOfficialUpdate: "٢٠٢٦/٠٤/٠٢",
    sourceUrl: "https://sfda.gov.sa",
    verified: true,
  },
  civil: {
    description: "موافقة الدفاع المدني على اشتراطات السلامة من الحريق للمنشأة.",
    descriptionEn: "Civil Defense approval on fire-safety requirements for the site.",
    requirements: ["نظام إنذار وإطفاء", "مخارج طوارئ"],
    requirementsEn: ["Fire alarm & suppression", "Emergency exits"],
    documents: ["مخطط السلامة", "عقد الصيانة"],
    documentsEn: ["Safety layout", "Maintenance contract"],
    eligibility: ["منشأة مطابقة لكود السلامة"],
    eligibilityEn: ["Site compliant with safety code"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٥ ١٠:٢٠",
    lastOfficialUpdate: "٢٠٢٥/١٢/١٥",
    sourceUrl: "https://998.gov.sa",
    verified: true,
    stale: true,
  },
  profession: {
    description: "ترخيص لمزاولة المهنة داخل المنشأة.",
    descriptionEn: "Professional practice license inside the establishment.",
    requirements: ["مؤهل أو شهادة خبرة", "فحص طبي"],
    requirementsEn: ["Qualification or experience", "Medical exam"],
    documents: ["السجل التجاري", "الشهادات المهنية"],
    documentsEn: ["Commercial Registration", "Professional certificates"],
    eligibility: ["مؤهل معتمد"],
    eligibilityEn: ["Accredited qualification"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٦ ٠٩:٠٠",
    lastOfficialUpdate: "٢٠٢٦/٠١/٢٠",
    sourceUrl: "https://balady.gov.sa",
    verified: true,
  },
  pharma: {
    description: "ترخيص إنشاء وتشغيل صيدلية من وزارة الصحة.",
    descriptionEn: "MoH license to establish and operate a pharmacy.",
    requirements: ["صيدلي مرخص", "موقع مطابق"],
    requirementsEn: ["Licensed pharmacist", "Compliant location"],
    documents: ["ترخيص الصيدلي", "السجل التجاري", "مخطط الموقع"],
    documentsEn: ["Pharmacist license", "Commercial Registration", "Site plan"],
    eligibility: ["صيدلي حاصل على الترخيص"],
    eligibilityEn: ["Certified pharmacist"],
    lastSyncedAt: "٢٠٢٦/٠٦/٢٩ ١٣:٤٥",
    lastOfficialUpdate: "٢٠٢٦/٠٣/٠١",
    sourceUrl: "https://moh.gov.sa",
    verified: true,
  },
  maroof: {
    description: "توثيق النشاط التجاري في منصة معروف لتعزيز ثقة العملاء.",
    descriptionEn: "Verify your business on Maroof to build customer trust.",
    requirements: ["سجل تجاري ساري"],
    requirementsEn: ["Valid CR"],
    documents: ["السجل التجاري"],
    documentsEn: ["Commercial Registration"],
    eligibility: ["منشأة مسجلة"],
    eligibilityEn: ["Registered establishment"],
    lastSyncedAt: "٢٠٢٦/٠٦/٣٠ ٠٧:٠٠",
    lastOfficialUpdate: "٢٠٢٦/٠٢/٢٥",
    sourceUrl: "https://maroof.sa",
    verified: true,
  },
};

export const DEFAULT_META: LicenseMeta = {
  description: "خدمة حكومية رسمية.",
  descriptionEn: "Official government service.",
  requirements: ["سجل تجاري ساري"],
  requirementsEn: ["Valid CR"],
  documents: ["الهوية الوطنية"],
  documentsEn: ["National ID"],
  eligibility: ["أهلية قانونية"],
  eligibilityEn: ["Legal capacity"],
  lastSyncedAt: "٢٠٢٦/٠٦/٣٠",
  lastOfficialUpdate: "—",
  sourceUrl: "https://my.gov.sa",
  verified: true,
};
